apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: weather-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml

commonLabels:
  app: weather-app
  version: v1.0.0

images:
- name: weather-app
  newTag: latest